BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 50
  LR: 9e-4
  MODEL_FILE_NAME: COHFACE_COHFACE_COHFACE_vire
  DATA:
    FS: 10
    DATASET: COHFLOW
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/path/to/dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/path/to/proc-dataset/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.5
    PREPROCESS :
      DATA_TYPE: ['Standardized'] # Check with LinearScaled
      LABEL_TYPE: Standardized # Raw, LinearScaled or DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 90
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 90
      CROP_FACE: False  # Disables face-based preprocessing
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 96
      W: 96
VALID:
  DATA:
    FS: 10
    DATASET: COHFLOW
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/path/to/dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/path/to/proc-dataset/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.5
    END: 0.7
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized # LinearScaled, DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 90
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 90
      CROP_FACE: False
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 96
      W: 96
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 10
    DATASET: COHFLOW
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/path/to/dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/path/to/proc-dataset/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.7
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized # Raw or DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 90
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 90
      CROP_FACE: False  # Disables face-based preprocessing
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 96
      W: 96
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: VIRENet
  MODEL_DIR: 
  LOSS: psd_mse
  VIRENET:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  MODEL_PATH:   ""